parameters:
  - name: NightlyFlag
    type: string
    values:
      - ' '
      - --nightly
    default: ' '

jobs:

- job: GetReleaseVersion
  displayName: Get Release Version
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - script: |
        cd script/vsts
        npm install
        node get-release-version.js ${{ parameters.NightlyFlag }}
      name: Version
