// Copyright (c) 2011 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//

#ifndef _V8EXCEPTION_CTOCPP_H
#define _V8EXCEPTION_CTOCPP_H

#ifndef USING_CEF_SHARED
#pragma message("Warning: "__FILE__" may be accessed wrapper-side only")
#else // USING_CEF_SHARED

#include "include/cef.h"
#include "include/cef_capi.h"
#include "libcef_dll/ctocpp/ctocpp.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefV8ExceptionCToCpp
    : public CefCToCpp<CefV8ExceptionCToCpp, CefV8Exception, cef_v8exception_t>
{
public:
  CefV8ExceptionCToCpp(cef_v8exception_t* str)
      : CefCToCpp<CefV8ExceptionCToCpp, CefV8Exception, cef_v8exception_t>(
          str) {}
  virtual ~CefV8ExceptionCToCpp() {}

  // CefV8Exception methods
  virtual CefString GetMessage() OVERRIDE;
  virtual CefString GetSourceLine() OVERRIDE;
  virtual CefString GetScriptResourceName() OVERRIDE;
  virtual int GetLineNumber() OVERRIDE;
  virtual int GetStartPosition() OVERRIDE;
  virtual int GetEndPosition() OVERRIDE;
  virtual int GetStartColumn() OVERRIDE;
  virtual int GetEndColumn() OVERRIDE;
};

#endif // USING_CEF_SHARED
#endif // _V8EXCEPTION_CTOCPP_H

