window.keymap.bindKeys 'body'
  'meta-up': 'core:move-to-top'
  'meta-down': 'core:move-to-bottom'

window.keymap.bindKeys '.editor'
  'meta-right': 'move-to-end-of-line'
  'meta-left': 'move-to-beginning-of-line'
  'alt-left': 'move-to-beginning-of-word'
  'alt-right': 'move-to-end-of-word'
  'meta-shift-up': 'select-to-top'
  'meta-shift-down': 'select-to-bottom'
  'meta-shift-left': 'select-to-beginning-of-line'
  'meta-shift-right': 'select-to-end-of-line'
  'alt-shift-left': 'select-to-beginning-of-word'
  'alt-shift-right': 'select-to-end-of-word'
  'alt-backspace': 'backspace-to-beginning-of-word'
  'alt-delete': 'delete-to-end-of-word'
