window.keymap.bindKeys 'body'
  'alt-meta-i': 'toggle-dev-tools'
  'meta-w': 'core:close'
  up: 'core:move-up'
  down: 'core:move-down'
  left: 'core:move-left'
  right: 'core:move-right'
  'shift-up': 'core:select-up'
  'shift-down': 'core:select-down'
  'shift-left': 'core:select-left'
  'shift-right': 'core:select-right'
  'meta-a': 'core:select-all'
  'backspace': 'core:backspace'
  'shift-backspace': 'core:backspace'
  'delete': 'core:delete'
  'meta-z': 'core:undo'
  'meta-Z': 'core:redo'
  'meta-x': 'core:cut'
  'meta-c': 'core:copy'
  'meta-v': 'core:paste'
  pageup: 'core:page-up'
  pagedown: 'core:page-down'

  'meta-S': 'root-view:save-all'
  'meta-+': 'root-view:increase-font-size'
  'meta--': 'root-view:decrease-font-size'
  'ctrl-w w': 'root-view:focus-next-pane'
