// Copyright (c) 2012 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//

#include "libcef_dll/cpptoc/menu_handler_cpptoc.h"
#include "libcef_dll/ctocpp/browser_ctocpp.h"


// MEMBER FUNCTIONS - Body may be edited by hand.

int CEF_CALLBACK menu_handler_on_before_menu(struct _cef_menu_handler_t* self,
    cef_browser_t* browser, const struct _cef_menu_info_t* menuInfo) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return 0;
  // Verify param: browser; type: refptr_diff
  DCHECK(browser);
  if (!browser)
    return 0;
  // Verify param: menuInfo; type: struct_byref_const
  DCHECK(menuInfo);
  if (!menuInfo)
    return 0;

  // Translate param: menuInfo; type: struct_byref_const
  CefMenuInfo menuInfoObj;
  if (menuInfo)
    menuInfoObj.Set(*menuInfo, false);

  // Execute
  bool _retval = CefMenuHandlerCppToC::Get(self)->OnBeforeMenu(
      CefBrowserCToCpp::Wrap(browser),
      menuInfoObj);

  // Return type: bool
  return _retval;
}

void CEF_CALLBACK menu_handler_get_menu_label(struct _cef_menu_handler_t* self,
    cef_browser_t* browser, enum cef_menu_id_t menuId, cef_string_t* label) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return;
  // Verify param: browser; type: refptr_diff
  DCHECK(browser);
  if (!browser)
    return;
  // Verify param: label; type: string_byref
  DCHECK(label);
  if (!label)
    return;

  // Translate param: label; type: string_byref
  CefString labelStr(label);

  // Execute
  CefMenuHandlerCppToC::Get(self)->GetMenuLabel(
      CefBrowserCToCpp::Wrap(browser),
      menuId,
      labelStr);
}

int CEF_CALLBACK menu_handler_on_menu_action(struct _cef_menu_handler_t* self,
    cef_browser_t* browser, enum cef_menu_id_t menuId) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return 0;
  // Verify param: browser; type: refptr_diff
  DCHECK(browser);
  if (!browser)
    return 0;

  // Execute
  bool _retval = CefMenuHandlerCppToC::Get(self)->OnMenuAction(
      CefBrowserCToCpp::Wrap(browser),
      menuId);

  // Return type: bool
  return _retval;
}


// CONSTRUCTOR - Do not edit by hand.

CefMenuHandlerCppToC::CefMenuHandlerCppToC(CefMenuHandler* cls)
    : CefCppToC<CefMenuHandlerCppToC, CefMenuHandler, cef_menu_handler_t>(cls) {
  struct_.struct_.on_before_menu = menu_handler_on_before_menu;
  struct_.struct_.get_menu_label = menu_handler_get_menu_label;
  struct_.struct_.on_menu_action = menu_handler_on_menu_action;
}

#ifndef NDEBUG
template<> long CefCppToC<CefMenuHandlerCppToC, CefMenuHandler,
    cef_menu_handler_t>::DebugObjCt = 0;
#endif

