<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rjs</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>RJS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ruby.rails.rjs</string>
	<key>uuid</key>
	<string>A6AE60CD-18CA-4474-BE7A-5255BC3EF083</string>
</dict>
</plist>
