jobs:
  - job: Windows
    dependsOn: GetReleaseVersion
    timeoutInMinutes: 180
    strategy:
      maxParallel: 2
      matrix:
        x64:
          buildArch: x64
          RunCoreMainTests: true
        x86:
          buildArch: x86
          RunCoreMainTests: true

    pool:
      vmImage: vs2017-win2016

    variables:
      AppName: $[ dependencies.GetReleaseVersion.outputs['Version.AppName'] ]
      ReleaseVersion: $[ dependencies.GetReleaseVersion.outputs['Version.ReleaseVersion'] ]
      IsReleaseBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsReleaseBranch'] ]
      IsSignedZipBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsSignedZipBranch'] ]

    steps:
      - template: templates/preparation.yml

      - template: templates/cache.yml
        parameters:
          OS: windows

      - template: templates/bootstrap.yml

      - script: node script\vsts\windows-run.js script\lint.cmd
        env:
          BUILD_ARCH: $(buildArch)
        displayName: Run linter

      - template: templates/build.yml

      - template: templates/test.yml

      - pwsh: |
          if ($env:BUILD_ARCH -eq "x64") {
            $env:FileID="-x64"
          } else {
            $env:FileID=""
          }
          echo "##vso[task.setvariable variable=FileID]$env:FileID" # Azure syntax
        env:
          BUILD_ARCH: $(buildArch)
        displayName: Set FileID based on the arch

      - template: templates/publish.yml
        parameters:
          artifacts:
            - filename: atom$(FileID)-windows.zip
              dir: $(Build.SourcesDirectory)/out
              condition: and( succeeded(), or( eq(variables['BUILD_ARCH'], 'x64'), ne(variables['Build.Reason'], 'PullRequest') ) )
            - filename: AtomSetup$(FileID).exe
              dir: $(Build.SourcesDirectory)/out
              condition: and(succeeded(), eq(variables['IsReleaseBranch'], 'true'))
            - filename: $(AppName)$(FileID)-$(ReleaseVersion)-full.nupkg
              dir: $(Build.SourcesDirectory)/out
              condition: and(succeeded(), eq(variables['IsReleaseBranch'], 'true'))
            - filename: $(AppName)$(FileID)-$(ReleaseVersion)-delta.nupkg
              dir: $(Build.SourcesDirectory)/out
              condition: and(succeeded(), eq(variables['IsReleaseBranch'], 'true'))
              continueOnError: true # Nightly builds don't produce delta packages yet, so don't fail the build
            - filename: RELEASES$(FileID)
              dir: $(Build.SourcesDirectory)/out
              condition: and(succeeded(), eq(variables['IsReleaseBranch'], 'true'))

  - job: Windows_RendererTests
    dependsOn: Windows
    timeoutInMinutes: 180
    strategy:
      maxParallel: 2
      matrix:
        x64_Renderer_Test1:
          RunCoreMainTests: false
          RunCoreRendererTests: 1
          buildArch: x64
        x64_Renderer_Test2:
          RunCoreMainTests: false
          RunCoreRendererTests: 2
          buildArch: x64

    pool:
      vmImage: vs2017-win2016

    variables:
      AppName: $[ dependencies.GetReleaseVersion.outputs['Version.AppName'] ]
      ReleaseVersion: $[ dependencies.GetReleaseVersion.outputs['Version.ReleaseVersion'] ]
      IsReleaseBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsReleaseBranch'] ]
      IsSignedZipBranch: $[ dependencies.GetReleaseVersion.outputs['Version.IsSignedZipBranch'] ]

    steps:
      - template: templates/preparation.yml

      - template: templates/cache.yml
        parameters:
          OS: windows

      - template: templates/bootstrap.yml

      # Downloading the build artifacts
      - pwsh: |
          if ($env:BUILD_ARCH -eq "x64") {
            $env:FileID="-x64"
            echo "##vso[task.setvariable variable=FileID]$env:FileID" # Azure syntax
          }
        env:
          BUILD_ARCH: $(buildArch)
        displayName: Set FileID based on the arch

      - template: templates/download-unzip.yml
        parameters:
          artifacts:
            -  atom$(FileID)-windows.zip

      #  Core renderer tests
      - template: templates/test.yml
