#!/usr/bin/env node --harmony_collections
var cp = require('./utils/child-process-wrapper.js');
var path = require('path');

process.chdir(path.dirname(__dirname));

cp.safeExec('node script/bootstrap', function() {
  var gruntPath = path.join('build', 'node_modules', 'grunt-cli', 'bin', 'grunt');
  var args = [gruntPath, '--gruntfile', path.resolve('build', 'Gruntfile.coffee')];
  args = args.concat(process.argv.slice(2));
  cp.safeSpawn(process.execPath, args, process.exit);
});
