#!/bin/sh

set -e

cd "$(dirname "$0")/.."

rm -rf ~/.atom
rm -rf /tmp/atom-coffee-cache
git clean -dff

./script/bootstrap
./node_modules/.bin/apm clean
./node_modules/.bin/grunt ci --stack --no-color
