SET BUILD_ATOM_RELEASES_S3_KEY=%BUILD_ATOM_WIN_RELEASES_S3_KEY%
SET BUILD_ATOM_RELEASES_S3_SECRET=%BUILD_ATOM_WIN_RELEASES_S3_SECRET%
SET BUILD_ATOM_RELEASES_S3_BUCKET=%BUILD_ATOM_WIN_RELEASES_S3_BUCKET%

ECHO Here I go Windowsing again

@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\cibuild" %*
) ELSE (
  node  "%~dp0\cibuild" %*
)
