#!/usr/bin/env node
var cp = require('./utils/child-process-wrapper.js');
var path = require('path');

process.chdir(path.dirname(__dirname));

cp.safeExec('node script/bootstrap', function() {
  var gruntPath = path.join('build', 'node_modules', '.bin', 'grunt');
  cp.safeExec(gruntPath + ' ci --gruntfile build/Gruntfile.coffee --stack --no-color', function() {
    process.exit(0);
  });
});
