#!/bin/bash

set -e

export ATOM_ACCESS_TOKEN=$BUILD_ATOM_LINUX_ACCESS_TOKEN

if [ -d /usr/local/share/nodenv ]; then
  export NODENV_ROOT=/usr/local/share/nodenv
  export PATH=/usr/local/share/nodenv/bin:/usr/local/share/nodenv/shims:$PATH
  export NODENV_VERSION="v0.10.21"
fi

script/cibuild
