#!/bin/bash

set -e

export ATOM_ACCESS_TOKEN=$BUILD_ATOM_LINUX_ACCESS_TOKEN
export BUILD_ATOM_RELEASES_S3_KEY=$BUILD_ATOM_LINUX_RELEASES_S3_KEY
export BUILD_ATOM_RELEASES_S3_SECRET=$BUILD_ATOM_LINUX_RELEASES_S3_SECRET
export BUILD_ATOM_RELEASES_S3_BUCKET=$BUILD_ATOM_LINUX_RELEASES_S3_BUCKET

if [ -d /usr/local/share/nodenv ]; then
  export NODENV_ROOT=/usr/local/share/nodenv
  export PATH=/usr/local/share/nodenv/bin:/usr/local/share/nodenv/shims:$PATH
  export NODENV_VERSION="v0.10.21"
fi

script/cibuild
