#!/bin/sh
# This can only be run by xcode or xcodebuild!

set -e

COMPILED_SOURCES_DIR="${1}"
RESOUCES_PATH="$BUILT_PRODUCTS_DIR/Atom.app/Contents/Resources/app"

# Copy non-coffee/cson/less files into bundle
rsync --archive --recursive \
      --exclude="src/**.coffee" \
      --exclude="src/**.cson" \
      --exclude="themes/**.cson" \
      --exclude="src/**.less" \
      --exclude="static/**.less" \
      --exclude="themes/**.less" \
      node_modules src static vendor spec benchmark themes dot-atom atom.sh package.json \
      "${COMPILED_SOURCES_DIR}/" "$RESOUCES_PATH"
