#!/bin/sh
# This can only be run by xcode or xcodebuild!

set -e

COMPILED_SOURCES_DIR="${1}"
RESOURCES_PATH="${BUILT_PRODUCTS_DIR}/Atom.app/Contents/Resources"
APP_PATH="${RESOURCES_PATH}/app"

# Copy non-coffee/cson/less files into bundle
rsync --archive --recursive \
      --exclude="src/**.coffee" \
      --exclude="src/**.cson" \
      --exclude="themes/**.cson" \
      --exclude="src/**.less" \
      --exclude="static/**.less" \
      --exclude="themes/**.less" \
      node_modules src static vendor spec benchmark themes dot-atom atom.sh package.json \
      "${COMPILED_SOURCES_DIR}/" "${APP_PATH}"

# Copy Mac specific files to bundle
rsync --archive --recursive \
      --exclude="*.plist" \
      resources/mac/* "${RESOURCES_PATH}"
