#!/bin/sh
# This can only be run by xcodebuild!

# Because of the way xcodebuild invokes external scripts we need to load
# The Setup's environment ourselves. If this isn't done, things like the
# node shim won't be able to find the stuff they need.

if [ -f /opt/github/env.sh ]; then
  source /opt/github/env.sh
fi

rake --trace copy-files-to-bundle
