#!/bin/sh

SOURCE_SCRIPTS_DIR="$PROJECT_DIR/HTML"
DESTINATION_SCRIPTS_DIR="$BUILT_PRODUCTS_DIR/$CONTENTS_FOLDER_PATH/Resources/"

cp -r "$SOURCE_SCRIPTS_DIR" "$DESTINATION_SCRIPTS_DIR"
echo "$DESTINATION_SCRIPTS_DIR"
