#!/bin/sh

set -e

# This entire file is a hack so that constructicon can build Atom via
# xcode

cd "$(dirname "$0")/.."
./script/bootstrap
./node_modules/.bin/grunt --build-dir="$BUILT_PRODUCTS_DIR build"

echo <<OUTPUT_FOR_CONSTRUCTICON
TARGET_BUILD_DIR=$BUILT_PRODUCTS_DIR
FULL_PRODUCT_NAME=Atom.app
PRODUCT_NAME=Atom
OUTPUT_FOR_CONSTRUCTICON
