#!/bin/sh
#/ Usage: download [-f] [-s] [-b cef-branch] [-r cef-revision] [-d url/to/prebuilt/cef] path/for/extraction
#/ Download and extract prebuilt CEF.
#/
#/ Options:
#/   -f            Overwrite path/for/extraction if it already exists.
#/   -s            Download debugging symbols as well.
#/   -b            CEF branch.
#/   -r            CEF revision.
#/   -d            Where to download binaries.
#/   -h            Show this message.

set -e

usage() {
  grep '^#/' <"$0"| cut -c4-
}

DISTURL="https://github-janky-artifacts.s3.amazonaws.com/prebuilt-cef"

while getopts ":fsb:r:d:h" OPTION; do
  case ${OPTION} in
    f)
      FORCE=1
      ;;
    s)
      SYMBOLS=1
      ;;
    b)
      CEF_BRANCH=${OPTARG}
      ;;
    r)
      CEF_REVISION=${OPTARG}
      ;;
    d)
      DISTURL=${OPTARG}
      ;;
    h)
      usage
      exit 0
      ;;
    ?)
      echo "Unknown option -${OPTARG}"
      usage
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))

if [ -z "${1}" ]; then
  usage
  exit 1
fi

if [ "$(uname)" = "Darwin" ]; then
  OS_TYPE=macosx
else
  OS_TYPE=linux
fi
CEF_BASENAME="cef_binary_3.${CEF_BRANCH}.${CEF_REVISION}_${OS_TYPE}"
CEF_SYMBOLS_BASENAME="${CEF_BASENAME}_symbols"

TEMP_DIR=$(mktemp -d -t prebuilt-cef-download.XXXXXX)
trap "rm -rf \"${TEMP_DIR}\"" EXIT

# See if we've already downloaded this version.
grep -E "^CEF Version:[[:space:]]+3\.${CEF_BRANCH}\.${CEF_REVISION}$" "${1}/README.txt" >/dev/null 2>&1 || {
  if [ -e "${1}" ] && [ "${FORCE}" != "1" ]; then
    echo >&2 "Error: ${1} already exists. Pass -f if you want to overwrite it."
    exit 1
  fi

  rm -rf "${1}"
  mkdir -p "${1}"

  echo "Downloading/extracting CEF3 branch ${CEF_BRANCH} r${CEF_REVISION}..."
  curl --progress-bar "${DISTURL}/${CEF_BASENAME}.zip" > "${TEMP_DIR}/cef.zip"
  unzip -q "${TEMP_DIR}/cef.zip" -d "${TEMP_DIR}"
  mv "${TEMP_DIR}/${CEF_BASENAME}"/* "${1}"
}

if [ "${SYMBOLS}" != "1" ]; then
  exit 0
fi

echo "Downloading/extracting symbols for CEF3 branch ${CEF_BRANCH} r${CEF_REVISION}..."
curl --progress-bar "${DISTURL}/${CEF_SYMBOLS_BASENAME}.zip" > "${TEMP_DIR}/symbols.zip"
unzip -q "${TEMP_DIR}/symbols.zip" -d "${TEMP_DIR}"
mv "${TEMP_DIR}/${CEF_SYMBOLS_BASENAME}"/* "${1}/Release"
