#!/bin/sh

set -e

cd "$(dirname $0)/.."

file_list() {
  while read file; do
    echo "      '${file}',"
  done
}

cat > sources.gypi <<EOF
{
  'variables': {
    'compiled_sources_dir': '<(INTERMEDIATE_DIR)/atom-resources',
    'compiled_sources_dir_xcode': '\${INTERMEDIATE_DIR}/atom-resources',
    'coffee_sources': [
$(find src static vendor -type file -name '*.coffee' | file_list)
    ],
    'cson_sources': [
$(find src static themes vendor -type file -name '*.cson' | file_list)
    ],
    'less_sources': [
$(find src static themes -type file -name '*.less' | file_list)
    ],
  },
}
EOF
