#!/usr/bin/env node
var path = require('path');
process.env.ATOM_RESOURCE_PATH = path.resolve(__dirname, '..');
var runGrunt = require('./utils/run-grunt.js');

// build/node_modules/.bin/grunt "$@"
var args = process.argv.slice(2);
runGrunt(args, process.exit);
