#!/bin/bash

SPEC_FILE="$1"
DESKTOP_FILE="$2"

RPM_BUILD_ROOT=~/rpmbuild
ARCH=`uname -m`

rpmdev-setuptree

cp -r /tmp/atom-build/Atom/* $RPM_BUILD_ROOT/BUILD
cp $SPEC_FILE $RPM_BUILD_ROOT/SPECS
cp ./atom.sh $RPM_BUILD_ROOT/BUILD
cp $DESKTOP_FILE $RPM_BUILD_ROOT/BUILD

rpmbuild -ba $SPEC_FILE
cp $RPM_BUILD_ROOT/RPMS/$ARCH/atom-*.rpm "./"

rm -rf $RPM_BUILD_ROOT
