#!/bin/sh

echo "Downloading node..."
curl -s -O http://nodejs.org/dist/v0.10.22/node-v0.10.22-darwin-x64.tar.gz
tar -zxf node-v0.10.22-darwin-x64.tar.gz
export PATH=$PWD/node-v0.10.22-darwin-x64/bin:$PATH

./script/test

exit
