#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )/.."

if [[ $1 == '-s' ]]; then
  SYMBOLS=1
  shift
fi

if [ -z $1 ]; then
  TARGET='cef'
else
  TARGET=$1
fi

DISTURL="https://gh-contractor-zcbenz.s3.amazonaws.com/cefode3/prebuilt-cef"

TEMP_DIR=$(mktemp -d -t prebuilt-cef-download.XXXXXX)
trap "rm -rf \"${TEMP_DIR}\"" EXIT

# Latest version
if ! LATEST_VERSION=$(curl -fsSkL $DISTURL/version); then
  exit 1;
fi

# Current version
CURRENT_VERSION=`cat cef/version 2>&1`

if [[ $LATEST_VERSION != $CURRENT_VERSION ]]; then
  echo "Downloading/extracting cefode3 u${LATEST_VERSION}..."
  if [ -t 1 ] ; then # If run from the terminal
    CURL_ARGS="--progress-bar"
  else
    CURL_ARGS="-fsS"
  fi
  curl $CURL_ARGS "${DISTURL}/cef_binary_latest.zip" > "${TEMP_DIR}/cef.zip"
  unzip -q "${TEMP_DIR}/cef.zip" -d "${TEMP_DIR}"
  [ -e "${TARGET}" ] && rm -rf "${TARGET}"
  mv "${TEMP_DIR}"/*_macosx "${TARGET}"
  echo ${LATEST_VERSION} > 'cef/version'
fi

if [[ "${SYMBOLS}" != "1" ]]; then
  exit 0
fi

echo "Downloading/extracting symbols for cefode3 u${LATEST_VERSION}..."
curl --progress-bar "${DISTURL}/cef_binary_latest_symbols.zip" > "${TEMP_DIR}/symbols.zip"
unzip -q "${TEMP_DIR}/symbols.zip" -d "${TEMP_DIR}"
mv "${TEMP_DIR}"/*_macosx_symbols/* "${TARGET}/Release"
