#!/bin/sh

set -e

BUILT_PRODUCTS_DIR=$1
PLIST_PATH="$BUILT_PRODUCTS_DIR/Atom.app/Contents/Info.plist"
HELPER_PLIST_PATH="$BUILT_PRODUCTS_DIR/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/Info.plist"

# Copy custom plist files
cp resources/mac/atom-Info.plist "$PLIST_PATH"
cp resources/mac/helper-Info.plist "$HELPER_PLIST_PATH"

# Update version
VERSION=$(git rev-parse --short HEAD | tr -d "\n")
echo $VERSION > "$BUILT_PRODUCTS_DIR/Atom.app/Contents/Resources/version"
/usr/libexec/PlistBuddy -c "Set CFBundleShortVersionString $VERSION" "$PLIST_PATH"
/usr/libexec/PlistBuddy -c "Set CFBundleVersion $VERSION" "$PLIST_PATH"
/usr/libexec/PlistBuddy -c "Set CFBundleShortVersionString $VERSION" "$HELPER_PLIST_PATH"
/usr/libexec/PlistBuddy -c "Set CFBundleVersion $VERSION" "$HELPER_PLIST_PATH"
