#!/bin/sh

# From root of libgit2 repo:
# mkdir build
# cd build
# cmake .. -DCMAKE_INSTALL_PREFIX=~/github/atom/git2  -DCMAKE_OSX_ARCHITECTURES="i386;x86_64" -DCMAKE_BUILD_TYPE=Release -DTHREADSAFE=1 -DBUILD_CLAR=OFF

# cmake --build . --target install
#
# From root of atom repo:
# mv git2/lib/libgit2.0.17.0.dylib git2/frameworks/libgit2.0.17.0.dylib
# rm -fr git2/lib
# script/update-libgit2

# update the id of the dylib
install_name_tool -id @executable_path/libgit2.0.17.0.dylib git2/frameworks/libgit2.0.17.0.dylib

# Verify @executable_path is in the output of:
otool -L git2/frameworks/libgit2.0.17.0.dylib
