#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}" )/.."

TARGET=${1:-atom-shell}
DISTURL="https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell"
CURRENT_VERSION=$(cat "${TARGET}/version" 2>&1)
LATEST_VERSION=ea1f81aa5260fe2d4a844f18e0251278fbadc093 # v0.2.1

if [ -z "${LATEST_VERSION}" ] ; then
  echo "Could determine lastest version of atom-shell" >&2
  exit 1
fi

TEMP_DIR=/tmp/atom-cached-atom-shells/${LATEST_VERSION}

if [[ ${LATEST_VERSION} != ${CURRENT_VERSION} ]]; then
  if [ -d $TEMP_DIR ]; then
    echo "Using cached version of atom-shell ${LATEST_VERSION} from ${TEMP_DIR}"
  else
    echo "Downloading/extracting atom-shell ${LATEST_VERSION}..."
    mkdir -p $TEMP_DIR
    curl "${DISTURL}/${LATEST_VERSION}/atom-shell.zip" > "${TEMP_DIR}/atom-shell.zip"
    unzip -q "${TEMP_DIR}/atom-shell.zip" -d "${TEMP_DIR}"
    rm "${TEMP_DIR}/atom-shell.zip"
  fi
  [ -e "${TARGET}" ] && rm -rf "${TARGET}"
  cp -R "${TEMP_DIR}" "${TARGET}"
  echo ${LATEST_VERSION} > "${TARGET}/version"
fi
