<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>IR_Black</string>
	<key>settings</key>
	<array>
		<dict>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#000000</string>
				<key>caret</key>
				<string>#FFFFFF</string>
				<key>foreground</key>
				<string>#EDEDED</string>
				<key>invisibles</key>
				<string>#CAE2FB3D</string>
				<key>lineHighlight</key>
				<string>#FFFFFF24</string>
				<key>selection</key>
				<string>#333333</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Comment</string>
			<key>scope</key>
			<string>comment</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#7C7C7C</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Entity</string>
			<key>scope</key>
			<string>entity</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#FFD2A7</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Keyword</string>
			<key>scope</key>
			<string>keyword</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#96CBFE</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Keyword.control</string>
			<key>scope</key>
			<string>keyword.control</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#96CBFE</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Keyword.Operator</string>
			<key>scope</key>
			<string>keyword.operator</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#EDEDED</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Class</string>
			<key>scope</key>
			<string>entity.name.type</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>underline</string>
				<key>foreground</key>
				<string>#FFFFB6</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Support</string>
			<key>scope</key>
			<string>support</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#FFFFB6</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Storage</string>
			<key>scope</key>
			<string>storage</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#CFCB90</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Storage.modifier</string>
			<key>scope</key>
			<string>storage.modifier</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#96CBFE</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Constant</string>
			<key>scope</key>
			<string>constant</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#99CC99</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>String</string>
			<key>scope</key>
			<string>string</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>bold</string>
				<key>foreground</key>
				<string>#A8FF60</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Number</string>
			<key>scope</key>
			<string>constant.numeric</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>bold</string>
				<key>foreground</key>
				<string>#FF73FD</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Punctuation</string>
			<key>scope</key>
			<string>punctuation</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Variable</string>
			<key>scope</key>
			<string>variable</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#C6C5FE</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Invalid – Deprecated</string>
			<key>scope</key>
			<string>invalid.deprecated</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>italic underline</string>
				<key>foreground</key>
				<string>#FD5FF1</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Invalid – Illegal</string>
			<key>scope</key>
			<string>invalid.illegal</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#562D56BF</string>
				<key>foreground</key>
				<string>#FD5FF1</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>-----------------------------------</string>
			<key>settings</key>
			<dict/>
		</dict>
		<dict>
			<key>name</key>
			<string>♦ Embedded Source (Bright)</string>
			<key>scope</key>
			<string>text source</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#B1B3BA08</string>
				<key>fontStyle</key>
				<string></string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>♦ Entity inherited-class</string>
			<key>scope</key>
			<string>entity.other.inherited-class</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>italic</string>
				<key>foreground</key>
				<string>#9B5C2E</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>♦ String embedded-variable</string>
			<key>scope</key>
			<string>source string source</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#EDEDED</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>♦ String punctuation</string>
			<key>scope</key>
			<string>source string source punctuation.section.embedded</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#00A0A0</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>♦ String constant</string>
			<key>scope</key>
			<string>string constant</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#00A0A0</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>♦ String.regexp</string>
			<key>scope</key>
			<string>string.regexp</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#E9C062</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>♦ String.regexp.«special»</string>
			<key>scope</key>
			<string>string.regexp constant.character.escape, string.regexp source.ruby.embedded, string.regexp string.regexp.arbitrary-repitition</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#FF8000</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>♦ String.regexp.group</string>
			<key>scope</key>
			<string>string.regexp.group</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#FFFFFF0F</string>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#C6A24F</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>♦ String.regexp.character-class</string>
			<key>scope</key>
			<string>string.regexp.character-class</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#B18A3D</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>♦ String variable</string>
			<key>scope</key>
			<string>string variable</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#8A9A95</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>♦ Support.function</string>
			<key>scope</key>
			<string>support.function</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#DAD085</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>♦ Support.constant</string>
			<key>scope</key>
			<string>support.constant</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#FFD2A7</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>c C/C++ Preprocessor Line</string>
			<key>scope</key>
			<string>meta.preprocessor.c</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#8996A8</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>c C/C++ Preprocessor Directive</string>
			<key>scope</key>
			<string>meta.preprocessor.c keyword</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#AFC4DB</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>j Cast</string>
			<key>scope</key>
			<string>meta.cast</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>italic</string>
				<key>foreground</key>
				<string>#676767</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>✘ Doctype/XML Processing</string>
			<key>scope</key>
			<string>meta.sgml.html meta.doctype, meta.sgml.html meta.doctype entity, meta.sgml.html meta.doctype string, meta.xml-processing, meta.xml-processing entity, meta.xml-processing string</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#494949</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>✘ Meta.tag.«all»</string>
			<key>scope</key>
			<string>meta.tag, meta.tag entity</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>bold</string>
				<key>foreground</key>
				<string>#96CBFE</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>✘ Meta.tag.inline</string>
			<key>scope</key>
			<string>source entity.name.tag, source entity.other.attribute-name, meta.tag.inline, meta.tag.inline entity</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#96CBFE</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>✘ Meta.tag.attribute-name</string>
			<key>scope</key>
			<string>entity.other.attribute-name</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#FFD7B1</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>✘ Namespaces</string>
			<key>scope</key>
			<string>entity.name.tag.namespace, entity.other.attribute-name.namespace</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#E18964</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>§ css tag-name</string>
			<key>scope</key>
			<string>meta.selector.css entity.name.tag</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>underline</string>
				<key>foreground</key>
				<string>#96CBFE</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>§ css:pseudo-class</string>
			<key>scope</key>
			<string>meta.selector.css entity.other.attribute-name.tag.pseudo-class</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#8F9D6A</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>§ css#id</string>
			<key>scope</key>
			<string>meta.selector.css entity.other.attribute-name.id</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#8B98AB</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>§ css.class</string>
			<key>scope</key>
			<string>meta.selector.css entity.other.attribute-name.class</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#62B1FE</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>§ css property-name:</string>
			<key>scope</key>
			<string>support.type.property-name.css</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#EDEDED</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>§ css property-value;</string>
			<key>scope</key>
			<string>meta.property-group support.constant.property-value.css, meta.property-value support.constant.property-value.css</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#F9EE98</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>§ css @at-rule</string>
			<key>scope</key>
			<string>meta.preprocessor.at-rule keyword.control.at-rule</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#8693A5</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>§ css additional-constants</string>
			<key>scope</key>
			<string>meta.property-value support.constant.named-color.css, meta.property-value constant</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#87C38A</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>§ css constructor.argument</string>
			<key>scope</key>
			<string>meta.constructor.argument.css</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#8F9D6A</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>⎇ diff.header</string>
			<key>scope</key>
			<string>meta.diff, meta.diff.header</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#0E2231</string>
				<key>fontStyle</key>
				<string>italic</string>
				<key>foreground</key>
				<string>#F8F8F8</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>⎇ diff.deleted</string>
			<key>scope</key>
			<string>markup.deleted</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#420E09</string>
				<key>foreground</key>
				<string>#F8F8F8</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>⎇ diff.changed</string>
			<key>scope</key>
			<string>markup.changed</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#4A410D</string>
				<key>foreground</key>
				<string>#F8F8F8</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>⎇ diff.inserted</string>
			<key>scope</key>
			<string>markup.inserted</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#253B22</string>
				<key>foreground</key>
				<string>#F8F8F8</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>--------------------------------</string>
			<key>settings</key>
			<dict/>
		</dict>
		<dict>
			<key>name</key>
			<string>Markup: Italic</string>
			<key>scope</key>
			<string>markup.italic</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>italic</string>
				<key>foreground</key>
				<string>#E9C062</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Markup: Bold</string>
			<key>scope</key>
			<string>markup.bold</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>bold</string>
				<key>foreground</key>
				<string>#E9C062</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Markup: Underline</string>
			<key>scope</key>
			<string>markup.underline</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>underline</string>
				<key>foreground</key>
				<string>#E18964</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Markup: Quote</string>
			<key>scope</key>
			<string>markup.quote</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#FEE09C12</string>
				<key>fontStyle</key>
				<string>italic</string>
				<key>foreground</key>
				<string>#E1D4B9</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Markup: Heading</string>
			<key>scope</key>
			<string>markup.heading, markup.heading entity</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#632D04</string>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#FEDCC5</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Markup: List</string>
			<key>scope</key>
			<string>markup.list</string>
			<key>settings</key>
			<dict>
				<key>foreground</key>
				<string>#E1D4B9</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Markup: Raw</string>
			<key>scope</key>
			<string>markup.raw</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#B1B3BA08</string>
				<key>fontStyle</key>
				<string></string>
				<key>foreground</key>
				<string>#578BB3</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Markup: Comment</string>
			<key>scope</key>
			<string>markup comment</string>
			<key>settings</key>
			<dict>
				<key>fontStyle</key>
				<string>italic</string>
				<key>foreground</key>
				<string>#F67B37</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Markup: Separator</string>
			<key>scope</key>
			<string>meta.separator</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#242424</string>
				<key>foreground</key>
				<string>#60A633</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Log Entry</string>
			<key>scope</key>
			<string>meta.line.entry.logfile, meta.line.exit.logfile</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#EEEEEE29</string>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>Log Entry Error</string>
			<key>scope</key>
			<string>meta.line.error.logfile</string>
			<key>settings</key>
			<dict>
				<key>background</key>
				<string>#751012</string>
			</dict>
		</dict>
	</array>
	<key>uuid</key>
	<string>D039AEA9-9DD2-4237-A963-E84494B0B3FB</string>
</dict>
</plist>
