// Copyright (c) 2012 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//

#include "libcef_dll/cpptoc/download_item_callback_cpptoc.h"


// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK download_item_callback_cancel(
    struct _cef_download_item_callback_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return;

  // Execute
  CefDownloadItemCallbackCppToC::Get(self)->Cancel();
}


// CONSTRUCTOR - Do not edit by hand.

CefDownloadItemCallbackCppToC::CefDownloadItemCallbackCppToC(
    CefDownloadItemCallback* cls)
    : CefCppToC<CefDownloadItemCallbackCppToC, CefDownloadItemCallback,
        cef_download_item_callback_t>(cls) {
  struct_.struct_.cancel = download_item_callback_cancel;
}

#ifndef NDEBUG
template<> long CefCppToC<CefDownloadItemCallbackCppToC,
    CefDownloadItemCallback, cef_download_item_callback_t>::DebugObjCt = 0;
#endif

