// Copyright (c) 2012 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//

#include "libcef_dll/cpptoc/web_plugin_info_cpptoc.h"


// MEMBER FUNCTIONS - Body may be edited by hand.

cef_string_userfree_t CEF_CALLBACK web_plugin_info_get_name(
    struct _cef_web_plugin_info_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return NULL;

  // Execute
  CefString _retval = CefWebPluginInfoCppToC::Get(self)->GetName();

  // Return type: string
  return _retval.DetachToUserFree();
}

cef_string_userfree_t CEF_CALLBACK web_plugin_info_get_path(
    struct _cef_web_plugin_info_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return NULL;

  // Execute
  CefString _retval = CefWebPluginInfoCppToC::Get(self)->GetPath();

  // Return type: string
  return _retval.DetachToUserFree();
}

cef_string_userfree_t CEF_CALLBACK web_plugin_info_get_version(
    struct _cef_web_plugin_info_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return NULL;

  // Execute
  CefString _retval = CefWebPluginInfoCppToC::Get(self)->GetVersion();

  // Return type: string
  return _retval.DetachToUserFree();
}

cef_string_userfree_t CEF_CALLBACK web_plugin_info_get_description(
    struct _cef_web_plugin_info_t* self) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return NULL;

  // Execute
  CefString _retval = CefWebPluginInfoCppToC::Get(self)->GetDescription();

  // Return type: string
  return _retval.DetachToUserFree();
}


// CONSTRUCTOR - Do not edit by hand.

CefWebPluginInfoCppToC::CefWebPluginInfoCppToC(CefWebPluginInfo* cls)
    : CefCppToC<CefWebPluginInfoCppToC, CefWebPluginInfo,
        cef_web_plugin_info_t>(cls) {
  struct_.struct_.get_name = web_plugin_info_get_name;
  struct_.struct_.get_path = web_plugin_info_get_path;
  struct_.struct_.get_version = web_plugin_info_get_version;
  struct_.struct_.get_description = web_plugin_info_get_description;
}

#ifndef NDEBUG
template<> long CefCppToC<CefWebPluginInfoCppToC, CefWebPluginInfo,
    cef_web_plugin_info_t>::DebugObjCt = 0;
#endif

