name: Ada (GNAT)

on:
  push:
    branches: [ github/BigGuy573/atom/atom-doc-update-template ]
  pull_request:
    branches: [ github/BigGuy573/atom/atom-doc-update-template ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update && 
        sudo apt-get install gnat gprbuild

    - name: Build
      run: gprbuild -j0 -p
